variables:
  # Privacy Policy Override
  PRIVACY_POLICY_URL:
    type: string
    default: ""
  
  # Background Notifications
  BACKGROUND_NOTIFICATION_TITLE:
    type: string
    default: "Measuring your health and fitness data."
  BACKGROUND_NOTIFICATION_DESCRIPTION:
    type: string
    default: "The app is running in the background."
  
  # Individual Health Permissions (boolean flags)
  ENABLE_HEART_RATE:
    type: boolean
    default: true
  ENABLE_STEPS:
    type: boolean
    default: true
  ENABLE_WEIGHT:
    type: boolean
    default: true
  ENABLE_HEIGHT:
    type: boolean
    default: true
  ENABLE_CALORIES_BURNED:
    type: boolean
    default: true
  ENABLE_SLEEP:
    type: boolean
    default: true
  ENABLE_BLOOD_PRESSURE:
    type: boolean
    default: true
  ENABLE_BLOOD_GLUCOSE:
    type: boolean
    default: true
  ENABLE_BODY_FAT_PERCENTAGE:
    type: boolean
    default: true
  ENABLE_BASAL_METABOLIC_RATE:
    type: boolean
    default: true
  ENABLE_WALKING_SPEED:
    type: boolean
    default: true
  ENABLE_DISTANCE:
    type: boolean
    default: true
  ENABLE_OXYGEN_SATURATION:
    type: boolean
    default: true
  ENABLE_BODY_TEMPERATURE:
    type: boolean
    default: true
  
  # Background Jobs
  DISABLE_BACKGROUND_JOBS:
    type: boolean
    default: false
  
  # iOS Health Permission Descriptions
  HEALTH_SHARE_DESCRIPTION:
    type: string
    default: "App needs to share health data"
  HEALTH_UPDATE_DESCRIPTION:
    type: string
    default: "App needs to use health data"

platforms:
  android:
    xml:
      # Privacy Policy URL Override
      - resFile: values/strings.xml
        target: resources/string[@name="privacy_policy_url"]
        replace: |
          <string name="privacy_policy_url">$PRIVACY_POLICY_URL</string>
        condition: ne($PRIVACY_POLICY_URL ?? "", "")
      
      # Background Notifications
      - resFile: values/strings.xml
        target: resources/string[@name="background_notification_title"]
        replace: |
          <string name="background_notification_title">$BACKGROUND_NOTIFICATION_TITLE</string>
      - resFile: values/strings.xml
        target: resources/string[@name="background_notification_description"]
        replace: |
          <string name="background_notification_description">$BACKGROUND_NOTIFICATION_DESCRIPTION</string>
      
      # Create health_permissions.xml file
      - resFile: values/health_permissions.xml
        target: resources
        merge: |
          <resources>
            <array name="health_permissions">
            </array>
          </resources>
      
      # Heart Rate Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_HEART_RATE</item>
          <item>android.permission.health.WRITE_HEART_RATE</item>
        condition: eq($ENABLE_HEART_RATE, true)
      
      # Steps Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_STEPS</item>
          <item>android.permission.health.WRITE_STEPS</item>
        condition: eq($ENABLE_STEPS, true)
      
      # Weight Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_WEIGHT</item>
          <item>android.permission.health.WRITE_WEIGHT</item>
        condition: eq($ENABLE_WEIGHT, true)
      
      # Height Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_HEIGHT</item>
          <item>android.permission.health.WRITE_HEIGHT</item>
        condition: eq($ENABLE_HEIGHT, true)
      
      # Calories Burned Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_TOTAL_CALORIES_BURNED</item>
          <item>android.permission.health.WRITE_TOTAL_CALORIES_BURNED</item>
        condition: eq($ENABLE_CALORIES_BURNED, true)
      
      # Sleep Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_SLEEP</item>
          <item>android.permission.health.WRITE_SLEEP</item>
        condition: eq($ENABLE_SLEEP, true)
      
      # Blood Pressure Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_BLOOD_PRESSURE</item>
          <item>android.permission.health.WRITE_BLOOD_PRESSURE</item>
        condition: eq($ENABLE_BLOOD_PRESSURE, true)
      
      # Blood Glucose Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_BLOOD_GLUCOSE</item>
          <item>android.permission.health.WRITE_BLOOD_GLUCOSE</item>
        condition: eq($ENABLE_BLOOD_GLUCOSE, true)
      
      # Body Fat Percentage Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_BODY_FAT</item>
          <item>android.permission.health.WRITE_BODY_FAT</item>
        condition: eq($ENABLE_BODY_FAT_PERCENTAGE, true)
      
      # Basal Metabolic Rate Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_BASAL_METABOLIC_RATE</item>
          <item>android.permission.health.WRITE_BASAL_METABOLIC_RATE</item>
        condition: eq($ENABLE_BASAL_METABOLIC_RATE, true)
      
      # Walking Speed Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_SPEED</item>
          <item>android.permission.health.WRITE_SPEED</item>
        condition: eq($ENABLE_WALKING_SPEED, true)
      
      # Distance Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_DISTANCE</item>
          <item>android.permission.health.WRITE_DISTANCE</item>
        condition: eq($ENABLE_DISTANCE, true)
      
      # Oxygen Saturation Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_OXYGEN_SATURATION</item>
          <item>android.permission.health.WRITE_OXYGEN_SATURATION</item>
        condition: eq($ENABLE_OXYGEN_SATURATION, true)
      
      # Body Temperature Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_BODY_TEMPERATURE</item>
          <item>android.permission.health.WRITE_BODY_TEMPERATURE</item>
        condition: eq($ENABLE_BODY_TEMPERATURE, true)
      
      # Background Job Permissions
      - resFile: values/health_permissions.xml
        target: resources/array[@name="health_permissions"]
        merge: |
          <item>android.permission.health.READ_HEALTH_DATA_IN_BACKGROUND</item>
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
    
    # AndroidManifest.xml permissions
    manifest:
      # Heart Rate Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_HEART_RATE" />
          <uses-permission android:name="android.permission.health.WRITE_HEART_RATE" />
        condition: eq($ENABLE_HEART_RATE, true)
      
      # Steps Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_STEPS" />
          <uses-permission android:name="android.permission.health.WRITE_STEPS" />
        condition: eq($ENABLE_STEPS, true)
      
      # Weight Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_WEIGHT" />
          <uses-permission android:name="android.permission.health.WRITE_WEIGHT" />
        condition: eq($ENABLE_WEIGHT, true)
      
      # Height Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_HEIGHT" />
          <uses-permission android:name="android.permission.health.WRITE_HEIGHT" />
        condition: eq($ENABLE_HEIGHT, true)
      
      # Calories Burned Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_TOTAL_CALORIES_BURNED" />
          <uses-permission android:name="android.permission.health.WRITE_TOTAL_CALORIES_BURNED" />
        condition: eq($ENABLE_CALORIES_BURNED, true)
      
      # Sleep Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_SLEEP" />
          <uses-permission android:name="android.permission.health.WRITE_SLEEP" />
        condition: eq($ENABLE_SLEEP, true)
      
      # Blood Pressure Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_BLOOD_PRESSURE" />
          <uses-permission android:name="android.permission.health.WRITE_BLOOD_PRESSURE" />
        condition: eq($ENABLE_BLOOD_PRESSURE, true)
      
      # Blood Glucose Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_BLOOD_GLUCOSE" />
          <uses-permission android:name="android.permission.health.WRITE_BLOOD_GLUCOSE" />
        condition: eq($ENABLE_BLOOD_GLUCOSE, true)
      
      # Body Fat Percentage Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_BODY_FAT" />
          <uses-permission android:name="android.permission.health.WRITE_BODY_FAT" />
        condition: eq($ENABLE_BODY_FAT_PERCENTAGE, true)
      
      # Basal Metabolic Rate Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_BASAL_METABOLIC_RATE" />
          <uses-permission android:name="android.permission.health.WRITE_BASAL_METABOLIC_RATE" />
        condition: eq($ENABLE_BASAL_METABOLIC_RATE, true)
      
      # Walking Speed Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_SPEED" />
          <uses-permission android:name="android.permission.health.WRITE_SPEED" />
        condition: eq($ENABLE_WALKING_SPEED, true)
      
      # Distance Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_DISTANCE" />
          <uses-permission android:name="android.permission.health.WRITE_DISTANCE" />
        condition: eq($ENABLE_DISTANCE, true)
      
      # Oxygen Saturation Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_OXYGEN_SATURATION" />
          <uses-permission android:name="android.permission.health.WRITE_OXYGEN_SATURATION" />
        condition: eq($ENABLE_OXYGEN_SATURATION, true)
      
      # Body Temperature Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_BODY_TEMPERATURE" />
          <uses-permission android:name="android.permission.health.WRITE_BODY_TEMPERATURE" />
        condition: eq($ENABLE_BODY_TEMPERATURE, true)
      
      # Background Job Permissions
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <uses-permission android:name="android.permission.health.READ_HEALTH_DATA_IN_BACKGROUND" />
          <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
          <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
          <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" />
          <uses-permission android:name="android.permission.HIGH_SAMPLING_RATE_SENSORS" />
          <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)

  ios:
    plist:
      - replace: false
        entries:
          - UIBackgroundModes:
              - fetch
              - processing
          - BGTaskSchedulerPermittedIdentifiers:
              - com.outsystems.health.default
          - NSHealthShareUsageDescription: "$HEALTH_SHARE_DESCRIPTION"
          - NSHealthUpdateUsageDescription: "$HEALTH_UPDATE_DESCRIPTION"
    entitlements:
      entries:
        - com.apple.developer.healthkit: "true"
        - com.apple.developer.healthkit.access: []
        - com.apple.developer.healthkit.background-delivery: "true"
        - com.apple.developer.healthkit.recalibrate-estimates: "true"