variables:
  # Privacy Policy Override
  PRIVACY_POLICY_URL:
    type: string
    default: ""
  
  # Background Notifications
  BACKGROUND_NOTIFICATION_TITLE:
    type: string
    default: "Measuring your health and fitness data."
  BACKGROUND_NOTIFICATION_DESCRIPTION:
    type: string
    default: "The app is running in the background."
  
  # Health Permissions - Read
  READ_HEART_RATE:
    type: boolean
    default: true
  READ_STEPS:
    type: boolean
    default: true
  READ_WEIGHT:
    type: boolean
    default: true
  READ_HEIGHT:
    type: boolean
    default: true
  READ_CALORIES_BURNED:
    type: boolean
    default: true
  READ_SLEEP:
    type: boolean
    default: true
  READ_BLOOD_PRESSURE:
    type: boolean
    default: true
  READ_BLOOD_GLUCOSE:
    type: boolean
    default: true
  READ_BODY_FAT_PERCENTAGE:
    type: boolean
    default: true
  READ_BASAL_METABOLIC_RATE:
    type: boolean
    default: true
  READ_WALKING_SPEED:
    type: boolean
    default: true
  READ_DISTANCE:
    type: boolean
    default: true
  READ_OXYGEN_SATURATION:
    type: boolean
    default: true
  READ_BODY_TEMPERATURE:
    type: boolean
    default: true

  # Health Permissions - Write
  WRITE_HEART_RATE:
    type: boolean
    default: true
  WRITE_STEPS:
    type: boolean
    default: true
  WRITE_WEIGHT:
    type: boolean
    default: true
  WRITE_HEIGHT:
    type: boolean
    default: true
  WRITE_CALORIES_BURNED:
    type: boolean
    default: true
  WRITE_SLEEP:
    type: boolean
    default: true
  WRITE_BLOOD_PRESSURE:
    type: boolean
    default: true
  WRITE_BLOOD_GLUCOSE:
    type: boolean
    default: true
  WRITE_BODY_FAT_PERCENTAGE:
    type: boolean
    default: true
  WRITE_BASAL_METABOLIC_RATE:
    type: boolean
    default: true
  WRITE_WALKING_SPEED:
    type: boolean
    default: true
  WRITE_DISTANCE:
    type: boolean
    default: true
  WRITE_OXYGEN_SATURATION:
    type: boolean
    default: true
  WRITE_BODY_TEMPERATURE:
    type: boolean
    default: true
  
  # Background Jobs
  DISABLE_BACKGROUND_JOBS:
    type: boolean
    default: false

platforms:
  android:
    xml:
      # Privacy Policy URL Override - Replace if exists
      - resFile: values/strings.xml
        target: resources/string[@name="privacy_policy_url"]
        replace: |
          <string name="privacy_policy_url">$PRIVACY_POLICY_URL</string>
        condition: ne($PRIVACY_POLICY_URL ?? "", "")
      
      # Privacy Policy URL Override - Create if doesn't exist
      - resFile: values/strings.xml
        target: resources
        inject: |
          <string name="privacy_policy_url">$PRIVACY_POLICY_URL</string>
        condition: ne($PRIVACY_POLICY_URL ?? "", "")
      
      # Background Notification Title - Replace if exists
      - resFile: values/strings.xml
        target: resources/string[@name="background_notification_title"]
        replace: |
          <string name="background_notification_title">$BACKGROUND_NOTIFICATION_TITLE</string>
      
      # Background Notification Title - Create if doesn't exist  
      - resFile: values/strings.xml
        target: resources
        inject: |
          <string name="background_notification_title">$BACKGROUND_NOTIFICATION_TITLE</string>
      
      # Background Notification Description - Replace if exists
      - resFile: values/strings.xml
        target: resources/string[@name="background_notification_description"]
        replace: |
          <string name="background_notification_description">$BACKGROUND_NOTIFICATION_DESCRIPTION</string>
      
      # Background Notification Description - Create if doesn't exist
      - resFile: values/strings.xml
        target: resources
        inject: |
          <string name="background_notification_description">$BACKGROUND_NOTIFICATION_DESCRIPTION</string>
    
    # AndroidManifest.xml permissions
    manifest:
      # Heart Rate Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEART_RATE" />
        condition: eq($READ_HEART_RATE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_HEART_RATE" />
        condition: eq($WRITE_HEART_RATE, true)
      
      # Steps Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_STEPS" />
        condition: eq($READ_STEPS, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_STEPS" />
        condition: eq($WRITE_STEPS, true)
      
      # Weight Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_WEIGHT" />
        condition: eq($READ_WEIGHT, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_WEIGHT" />
        condition: eq($WRITE_WEIGHT, true)
      
      # Height Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEIGHT" />
        condition: eq($READ_HEIGHT, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_HEIGHT" />
        condition: eq($WRITE_HEIGHT, true)
      
      # Calories Burned Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_TOTAL_CALORIES_BURNED" />
        condition: eq($READ_CALORIES_BURNED, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_TOTAL_CALORIES_BURNED" />
        condition: eq($WRITE_CALORIES_BURNED, true)
      
      # Sleep Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_SLEEP" />
        condition: eq($READ_SLEEP, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_SLEEP" />
        condition: eq($WRITE_SLEEP, true)
      
      # Blood Pressure Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BLOOD_PRESSURE" />
        condition: eq($READ_BLOOD_PRESSURE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BLOOD_PRESSURE" />
        condition: eq($WRITE_BLOOD_PRESSURE, true)
      
      # Blood Glucose Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BLOOD_GLUCOSE" />
        condition: eq($READ_BLOOD_GLUCOSE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BLOOD_GLUCOSE" />
        condition: eq($WRITE_BLOOD_GLUCOSE, true)
      
      # Body Fat Percentage Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BODY_FAT" />
        condition: eq($READ_BODY_FAT_PERCENTAGE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BODY_FAT" />
        condition: eq($WRITE_BODY_FAT_PERCENTAGE, true)
      
      # Basal Metabolic Rate Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BASAL_METABOLIC_RATE" />
        condition: eq($READ_BASAL_METABOLIC_RATE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BASAL_METABOLIC_RATE" />
        condition: eq($WRITE_BASAL_METABOLIC_RATE, true)
      
      # Walking Speed Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_SPEED" />
        condition: eq($READ_WALKING_SPEED, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_SPEED" />
        condition: eq($WRITE_WALKING_SPEED, true)
      
      # Distance Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_DISTANCE" />
        condition: eq($READ_DISTANCE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_DISTANCE" />
        condition: eq($WRITE_DISTANCE, true)
      
      # Oxygen Saturation Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_OXYGEN_SATURATION" />
        condition: eq($READ_OXYGEN_SATURATION, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_OXYGEN_SATURATION" />
        condition: eq($WRITE_OXYGEN_SATURATION, true)
      
      # Body Temperature Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BODY_TEMPERATURE" />
        condition: eq($READ_BODY_TEMPERATURE, true)

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BODY_TEMPERATURE" />
        condition: eq($WRITE_BODY_TEMPERATURE, true)
      
      # Background Job Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEALTH_DATA_IN_BACKGROUND" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.HIGH_SAMPLING_RATE_SENSORS" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)

  ios:
    plist:
      - replace: false
        entries:
          - UIBackgroundModes:
              - fetch
              - processing
          - BGTaskSchedulerPermittedIdentifiers:
              - com.outsystems.health.default
    entitlements:
    # Extensiblity Config does not currently support boolean values, so we need to use strings and convert them in a hook
      entries:
        - com.apple.developer.healthkit: true
        - com.apple.developer.healthkit.access: []
        - com.apple.developer.healthkit.background-delivery: true
        - com.apple.developer.healthkit.recalibrate-estimates: true