variables:
  # Privacy Policy Override
  PRIVACY_POLICY_URL:
    type: string
    default: ""
  
  # Background Notifications
  BACKGROUND_NOTIFICATION_TITLE:
    type: string
    default: "Measuring your health and fitness data."
  BACKGROUND_NOTIFICATION_DESCRIPTION:
    type: string
    default: "The app is running in the background."
  
  # Individual Health Permissions
  HEART_RATE:
    type: string
    default: ""
  STEPS:
    type: string
    default: ""
  WEIGHT:
    type: string
    default: ""
  HEIGHT:
    type: string
    default: ""
  CALORIES_BURNED:
    type: string
    default: ""
  SLEEP:
    type: string
    default: ""
  BLOOD_PRESSURE:
    type: string
    default: ""
  BLOOD_GLUCOSE:
    type: string
    default: ""
  BODY_FAT_PERCENTAGE:
    type: string
    default: ""
  BASAL_METABOLIC_RATE:
    type: string
    default: ""
  WALKING_SPEED:
    type: string
    default: ""
  DISTANCE:
    type: string
    default: ""
  OXYGEN_SATURATION:
    type: string
    default: ""
  BODY_TEMPERATURE:
    type: string
    default: ""

  # Group Health Permissions
  ALL_VARIABLES:
    type: string
    default: ""
  FITNESS_VARIABLES:
    type: string
    default: ""
  HEALTH_VARIABLES:
    type: string
    default: ""
  PROFILE_VARIABLES:
    type: string
    default: ""
  
  # Background Jobs
  DISABLE_BACKGROUND_JOBS:
    type: boolean
    default: false

platforms:
  android:
    xml:
      # Privacy Policy URL Override
      - resFile: values/strings.xml
        target: resources
        merge: |
          <resources>
            <string name="privacy_policy_url">$PRIVACY_POLICY_URL</string>
          </resources>
        condition: ne($PRIVACY_POLICY_URL ?? "", "")
      
      # Background Notification Title
      - resFile: values/strings.xml
        target: resources
        merge: |
          <resources>
            <string name="background_notification_title">$BACKGROUND_NOTIFICATION_TITLE</string>
          </resources>
      
      # Background Notification Description
      - resFile: values/strings.xml
        target: resources
        merge: |
          <resources>
            <string name="background_notification_description">$BACKGROUND_NOTIFICATION_DESCRIPTION</string>
          </resources>
    
    # AndroidManifest.xml permissions
    manifest:
      # Heart Rate Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEART_RATE" />
        condition: or(
          eq($HEART_RATE, "Read"),
          eq($HEART_RATE, "ReadWrite"),
          and(ne($HEART_RATE, "Write"), or(
            eq($HEALTH_VARIABLES, "Read"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_HEART_RATE" />
        condition: or(
          eq($HEART_RATE, "Write"),
          eq($HEART_RATE, "ReadWrite"),
          and(ne($HEART_RATE, "Read"), or(
            eq($HEALTH_VARIABLES, "Write"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Steps Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_STEPS" />
        condition: or(
          eq($STEPS, "Read"),
          eq($STEPS, "ReadWrite"),
          and(ne($STEPS, "Write"), or(
            eq($FITNESS_VARIABLES, "Read"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_STEPS" />
        condition: or(
          eq($STEPS, "Write"),
          eq($STEPS, "ReadWrite"),
          and(ne($STEPS, "Read"), or(
            eq($FITNESS_VARIABLES, "Write"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Weight Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_WEIGHT" />
        condition: or(
          eq($WEIGHT, "Read"),
          eq($WEIGHT, "ReadWrite"),
          and(ne($WEIGHT, "Write"), or(
            eq($PROFILE_VARIABLES, "Read"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_WEIGHT" />
        condition: or(
          eq($WEIGHT, "Write"),
          eq($WEIGHT, "ReadWrite"),
          and(ne($WEIGHT, "Read"), or(
            eq($PROFILE_VARIABLES, "Write"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Height Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEIGHT" />
        condition: or(
          eq($HEIGHT, "Read"),
          eq($HEIGHT, "ReadWrite"),
          and(ne($HEIGHT , "Write"), or(
            eq($PROFILE_VARIABLES, "Read"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_HEIGHT" />
        condition: or(
          eq($HEIGHT, "Write"),
          eq($HEIGHT, "ReadWrite"),
          and(ne($HEIGHT , "Read"), or(
            eq($PROFILE_VARIABLES, "Write"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Calories Burned Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_TOTAL_CALORIES_BURNED" />
        condition: or(
          eq($CALORIES_BURNED, "Read"),
          eq($CALORIES_BURNED, "ReadWrite"),
          and(ne($CALORIES_BURNED , "Write"), or(
            eq($FITNESS_VARIABLES, "Read"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_TOTAL_CALORIES_BURNED" />
        condition: or(
          eq($CALORIES_BURNED, "Write"),
          eq($CALORIES_BURNED, "ReadWrite"),
          and(ne($CALORIES_BURNED , "Read"), or(
            eq($FITNESS_VARIABLES, "Write"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Sleep Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_SLEEP" />
        condition: or(
          eq($SLEEP, "Read"),
          eq($SLEEP, "ReadWrite"),
          and(ne($SLEEP , "Write"), or(
            eq($HEALTH_VARIABLES, "Read"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_SLEEP" />
        condition: or(
          eq($SLEEP, "Write"),
          eq($SLEEP, "ReadWrite"),
          and(ne($SLEEP , "Read"), or(
            eq($HEALTH_VARIABLES, "Write"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Blood Pressure Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BLOOD_PRESSURE" />
        condition: or(
          eq($BLOOD_PRESSURE, "Read"),
          eq($BLOOD_PRESSURE, "ReadWrite"),
          and(ne($BLOOD_PRESSURE , "Write"), or(
            eq($HEALTH_VARIABLES, "Read"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BLOOD_PRESSURE" />
        condition: or(
          eq($BLOOD_PRESSURE, "Write"),
          eq($BLOOD_PRESSURE, "ReadWrite"),
          and(ne($BLOOD_PRESSURE , "Read"), or(
            eq($HEALTH_VARIABLES, "Write"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Blood Glucose Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BLOOD_GLUCOSE" />
        condition: or(
          eq($BLOOD_GLUCOSE, "Read"),
          eq($BLOOD_GLUCOSE, "ReadWrite"),
          and(ne($BLOOD_GLUCOSE , "Write"), or(
            eq($HEALTH_VARIABLES, "Read"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BLOOD_GLUCOSE" />
        condition: or(
          eq($BLOOD_GLUCOSE, "Write"),
          eq($BLOOD_GLUCOSE, "ReadWrite"),
          and(ne($BLOOD_GLUCOSE , "Read"), or(
            eq($HEALTH_VARIABLES, "Write"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Body Fat Percentage Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BODY_FAT" />
        condition: or(
          eq($BODY_FAT_PERCENTAGE, "Read"),
          eq($BODY_FAT_PERCENTAGE, "ReadWrite"),
          and(ne($BODY_FAT_PERCENTAGE , "Write"), or(
            eq($PROFILE_VARIABLES, "Read"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BODY_FAT" />
        condition: or(
          eq($BODY_FAT_PERCENTAGE, "Write"),
          eq($BODY_FAT_PERCENTAGE, "ReadWrite"),
          and(ne($BODY_FAT_PERCENTAGE , "Read"), or(
            eq($PROFILE_VARIABLES, "Write"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Basal Metabolic Rate Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BASAL_METABOLIC_RATE" />
        condition: or(
          eq($BASAL_METABOLIC_RATE, "Read"),
          eq($BASAL_METABOLIC_RATE, "ReadWrite"),
          and(ne($BASAL_METABOLIC_RATE , "Write"), or(
            eq($PROFILE_VARIABLES, "Read"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BASAL_METABOLIC_RATE" />
        condition: or(
          eq($BASAL_METABOLIC_RATE, "Write"),
          eq($BASAL_METABOLIC_RATE, "ReadWrite"),
          and(ne($BASAL_METABOLIC_RATE , "Read"), or(
            eq($PROFILE_VARIABLES, "Write"),
            eq($PROFILE_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Walking Speed Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_SPEED" />
        condition: or(
          eq($WALKING_SPEED, "Read"),
          eq($WALKING_SPEED, "ReadWrite"),
          and(ne($WALKING_SPEED , "Write"), or(
            eq($FITNESS_VARIABLES, "Read"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_SPEED" />
        condition: or(
          eq($WALKING_SPEED, "Write"),
          eq($WALKING_SPEED, "ReadWrite"),
          and(ne($WALKING_SPEED , "Read"), or(
            eq($FITNESS_VARIABLES, "Write"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Distance Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_DISTANCE" />
        condition: or(
          eq($DISTANCE, "Read"),
          eq($DISTANCE, "ReadWrite"),
          and(ne($DISTANCE , "Write"), or(
            eq($FITNESS_VARIABLES, "Read"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_DISTANCE" />
        condition: or(
          eq($DISTANCE, "Write"),
          eq($DISTANCE, "ReadWrite"),
          and(ne($DISTANCE , "Read"), or(
            eq($FITNESS_VARIABLES, "Write"),
            eq($FITNESS_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Oxygen Saturation Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_OXYGEN_SATURATION" />
        condition: or(
          eq($OXYGEN_SATURATION, "Read"),
          eq($OXYGEN_SATURATION, "ReadWrite"),
          and(ne($OXYGEN_SATURATION , "Write"), or(
            eq($HEALTH_VARIABLES, "Read"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_OXYGEN_SATURATION" />
        condition: or(
          eq($OXYGEN_SATURATION, "Write"),
          eq($OXYGEN_SATURATION, "ReadWrite"),
          and(ne($OXYGEN_SATURATION , "Read"), or(
            eq($HEALTH_VARIABLES, "Write"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Body Temperature Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_BODY_TEMPERATURE" />
        condition: or(
          eq($BODY_TEMPERATURE, "Read"),
          eq($BODY_TEMPERATURE, "ReadWrite"),
          and(ne($BODY_TEMPERATURE , "Write"), or(
            eq($HEALTH_VARIABLES, "Read"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Read"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.WRITE_BODY_TEMPERATURE" />
        condition: or(
          eq($BODY_TEMPERATURE, "Write"),
          eq($BODY_TEMPERATURE, "ReadWrite"),
          and(ne($BODY_TEMPERATURE , "Read"), or(
            eq($HEALTH_VARIABLES, "Write"),
            eq($HEALTH_VARIABLES, "ReadWrite"),
            eq($ALL_VARIABLES, "Write"),
            eq($ALL_VARIABLES, "ReadWrite")
          ))
        )
      
      # Background Job Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEALTH_DATA_IN_BACKGROUND" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.HIGH_SAMPLING_RATE_SENSORS" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)

  ios:
    plist:
      - replace: false
        entries:
          - UIBackgroundModes:
              - fetch
              - processing
          - BGTaskSchedulerPermittedIdentifiers:
              - com.outsystems.health.default
    entitlements:
    # Extensiblity Config does not currently support boolean values, so we need to use strings and convert them in a hook
      entries:
        - com.apple.developer.healthkit: true
        - com.apple.developer.healthkit.access: []
        - com.apple.developer.healthkit.background-delivery: true
        - com.apple.developer.healthkit.recalibrate-estimates: true