variables:
  # Privacy Policy Override
  PRIVACY_POLICY_URL:
    type: string
    default: ""
  
  # Background Notifications
  BACKGROUND_NOTIFICATION_TITLE:
    type: string
    default: "Measuring your health and fitness data."
  BACKGROUND_NOTIFICATION_DESCRIPTION:
    type: string
    default: "The app is running in the background."

  # Background Jobs
  DISABLE_BACKGROUND_JOBS:
    type: boolean
    default: false

platforms:
  android:
    xml:
      # Privacy Policy URL Override
      - resFile: values/strings.xml
        target: resources
        merge: |
          <resources>
            <string name="privacy_policy_url">$PRIVACY_POLICY_URL</string>
          </resources>
        condition: ne($PRIVACY_POLICY_URL ?? "", "")
      
      # Background Notification Title
      - resFile: values/strings.xml
        target: resources
        merge: |
          <resources>
            <string name="background_notification_title">$BACKGROUND_NOTIFICATION_TITLE</string>
          </resources>
      
      # Background Notification Description
      - resFile: values/strings.xml
        target: resources
        merge: |
          <resources>
            <string name="background_notification_description">$BACKGROUND_NOTIFICATION_DESCRIPTION</string>
          </resources>
    
    # AndroidManifest.xml permissions
    manifest:
      # Health Data History (older than 30 days)
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.READ_HEALTH_DATA_HISTORY" />

      # Background Job Permissions
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.health.READ_HEALTH_DATA_IN_BACKGROUND" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.HIGH_SAMPLING_RATE_SENSORS" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)
      
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
        condition: eq($DISABLE_BACKGROUND_JOBS, false)

  ios:
    plist:
      - replace: false
        entries:
          - UIBackgroundModes:
              - fetch
              - processing
          - BGTaskSchedulerPermittedIdentifiers:
              - com.outsystems.health.default
    entitlements:
    # Extensiblity Config does not currently support boolean values, so we need to use strings and convert them in a hook
      entries:
        - com.apple.developer.healthkit: true
        - com.apple.developer.healthkit.access: []
        - com.apple.developer.healthkit.background-delivery: true
        - com.apple.developer.healthkit.recalibrate-estimates: true